version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3.8.9-management
        restart: unless-stopped
        ports:
          - 5672:5672
          - 15672:15672
        
    mysql:
        image: mysql:8
        container_name: mysql-gateway
        ports:
          - 3306:3306
        restart: unless-stopped
        environment:        
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        entrypoint:
          sh -c "
            echo 'CREATE DATABASE IF NOT EXISTS sxs_gateway;' > /docker-entrypoint-initdb.d/init.sql;
            /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
          "
        command: ["--default-authentication-plugin=mysql_native_password"]
           
    #client-frontend:
        #image: sxs-client-frontend
        #restart: unless-stopped
        #ports:
            #- 80:3000
    
    gateway:
        restart: unless-stopped
        image: jaimetruman/sxs-gateway:v2
        ports:
            - 8080:8080
        depends_on:
            - mysql
            - rabbitmq
            - active-orders-redis
    
    client-order-event-dispatcher:
        image: jaimetruman/sxs-client-order-event-dispatcher:v1
        restart: unless-stopped
        ports:
            - 4000:4000 
        depends_on:
            - rabbitmq
            - gateway
    
    active-orders-redis: 
        image: redis:6.2-alpine
        restart: unless-stopped
        command: redis-server --requirepass 29oumr982oyvtpiou2
        ports:
            - 6379:6379