#apiVersion: v1
#kind: ServiceAccount
#metadata:
  #name: build-robot
#automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      #serviceAccountName: build-robot
      containers:
        - name: gateway
          image: jaimetruman/sxs-gateway
          ports:
            - containerPort: 8080
          resources: { }
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway